package com.simulator.bank.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity for the {@code otps} table in {@code saham_core_db}.
 *
 * <p>OTPs are generated by {@link com.simulator.bank.service.OtpService} and
 * verified during the provisioning activation step. They expire after 10 minutes
 * and lock after 3 failed attempts.
 *
 * <p><b>Security constraints:</b>
 * <ul>
 *   <li>{@code codeHash} — bcrypt hash of the 6-digit OTP. Never stored or logged in plaintext.</li>
 *   <li>After 3 failed {@code attempts}, the OTP is treated as locked and rejected.</li>
 *   <li>After {@code expiresAt}, the OTP is rejected regardless of attempt count.</li>
 * </ul>
 */
@Entity
@Table(name = "otps")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Otp {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "otp_id", updatable = false, nullable = false)
    private UUID otpId;

    /** Logical link to the card — not a FK constraint across the DB boundary. */
    @Column(name = "pan_unique_reference", nullable = false, length = 64)
    private String panUniqueReference;

    /** Opaque 8-char alphanumeric ID used to correlate delivery and verification. */
    @Column(name = "activation_method_id", nullable = false, length = 8)
    private String activationMethodId;

    /** bcrypt hash of the 6-digit OTP code. */
    @Column(name = "code_hash", nullable = false, length = 128)
    private String codeHash;

    /** Delivery channel: {@code SMS} or {@code EMAIL}. */
    @Column(name = "delivery_channel", nullable = false, length = 20)
    private String deliveryChannel;

    /** Timestamp after which this OTP is invalid (10-minute TTL). */
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    /** Marks OTP as consumed after successful verification. */
    @Column(name = "used", nullable = false)
    @Builder.Default
    private Boolean used = false;

    /** Number of failed verification attempts. Lockout after 3. */
    @Column(name = "attempts", nullable = false)
    @Builder.Default
    private Short attempts = 0;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private OffsetDateTime createdAt = OffsetDateTime.now();

    /** @return true if the OTP has expired or has been locked out */
    public boolean isExpiredOrLocked() {
        return used || attempts >= 3 || OffsetDateTime.now().isAfter(expiresAt);
    }
}
